//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/nCode/docueye/Source/DocuEye.Structurizr.DSL.Expressions/StructurizrDSLExpressions.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class StructurizrDSLExpressionsParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, ELEMENT=3, ELEMENT_TYPE=4, ELEMENT_PARENT=5, ELEMENT_TAG=6, 
		ELEMENT_TECHNOLOGY=7, ELEMENT_PROPERTIES=8, RELATIONSHIP=9, RELATIONSHIP_TAG=10, 
		RELATIONSHIP_PROPERTIES=11, RELATIONSHIP_SOURCE=12, RELATIONSHIP_DESTINATION=13, 
		VALUE=14, OR=15, AND=16, WILDCARD=17, DOT=18, EQUALS=19, NOTEQUALS=20, 
		RELATIONSHIP_POINTER=21, MORE_THAN=22, WHITESPACE=23;
	public const int
		RULE_generalExpression = 0, RULE_elementTypeExpr = 1, RULE_elementParentExpr = 2, 
		RULE_elementTagExpr = 3, RULE_elementTechnologyExpr = 4, RULE_elementPropertiesExpr = 5, 
		RULE_elementWithCouplingsExpr = 6, RULE_relationshipTagExpr = 7, RULE_relationshipPropertiesExpr = 8, 
		RULE_relationshipSourceExpr = 9, RULE_relationshipDestinationExpr = 10, 
		RULE_relationshipSpecifiedExpr = 11, RULE_relationshipAllExpr = 12, RULE_sourceElement = 13, 
		RULE_destinationElement = 14, RULE_relationshipPointer = 15, RULE_expressionValue = 16, 
		RULE_propertyName = 17, RULE_expressionConnector = 18;
	public static readonly string[] ruleNames = {
		"generalExpression", "elementTypeExpr", "elementParentExpr", "elementTagExpr", 
		"elementTechnologyExpr", "elementPropertiesExpr", "elementWithCouplingsExpr", 
		"relationshipTagExpr", "relationshipPropertiesExpr", "relationshipSourceExpr", 
		"relationshipDestinationExpr", "relationshipSpecifiedExpr", "relationshipAllExpr", 
		"sourceElement", "destinationElement", "relationshipPointer", "expressionValue", 
		"propertyName", "expressionConnector"
	};

	private static readonly string[] _LiteralNames = {
		null, "'['", "']'", null, null, null, null, null, null, null, null, null, 
		null, null, null, "'||'", "'&&'", "'*'", "'.'", "'=='", "'!='", "'->'", 
		"'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, "ELEMENT", "ELEMENT_TYPE", "ELEMENT_PARENT", "ELEMENT_TAG", 
		"ELEMENT_TECHNOLOGY", "ELEMENT_PROPERTIES", "RELATIONSHIP", "RELATIONSHIP_TAG", 
		"RELATIONSHIP_PROPERTIES", "RELATIONSHIP_SOURCE", "RELATIONSHIP_DESTINATION", 
		"VALUE", "OR", "AND", "WILDCARD", "DOT", "EQUALS", "NOTEQUALS", "RELATIONSHIP_POINTER", 
		"MORE_THAN", "WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "StructurizrDSLExpressions.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static StructurizrDSLExpressionsParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public StructurizrDSLExpressionsParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public StructurizrDSLExpressionsParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class GeneralExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ElementTypeExprContext[] elementTypeExpr() {
			return GetRuleContexts<ElementTypeExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElementTypeExprContext elementTypeExpr(int i) {
			return GetRuleContext<ElementTypeExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElementParentExprContext[] elementParentExpr() {
			return GetRuleContexts<ElementParentExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElementParentExprContext elementParentExpr(int i) {
			return GetRuleContext<ElementParentExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElementTagExprContext[] elementTagExpr() {
			return GetRuleContexts<ElementTagExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElementTagExprContext elementTagExpr(int i) {
			return GetRuleContext<ElementTagExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElementTechnologyExprContext[] elementTechnologyExpr() {
			return GetRuleContexts<ElementTechnologyExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElementTechnologyExprContext elementTechnologyExpr(int i) {
			return GetRuleContext<ElementTechnologyExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElementPropertiesExprContext[] elementPropertiesExpr() {
			return GetRuleContexts<ElementPropertiesExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElementPropertiesExprContext elementPropertiesExpr(int i) {
			return GetRuleContext<ElementPropertiesExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElementWithCouplingsExprContext[] elementWithCouplingsExpr() {
			return GetRuleContexts<ElementWithCouplingsExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ElementWithCouplingsExprContext elementWithCouplingsExpr(int i) {
			return GetRuleContext<ElementWithCouplingsExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationshipTagExprContext[] relationshipTagExpr() {
			return GetRuleContexts<RelationshipTagExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationshipTagExprContext relationshipTagExpr(int i) {
			return GetRuleContext<RelationshipTagExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationshipPropertiesExprContext[] relationshipPropertiesExpr() {
			return GetRuleContexts<RelationshipPropertiesExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationshipPropertiesExprContext relationshipPropertiesExpr(int i) {
			return GetRuleContext<RelationshipPropertiesExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationshipSourceExprContext[] relationshipSourceExpr() {
			return GetRuleContexts<RelationshipSourceExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationshipSourceExprContext relationshipSourceExpr(int i) {
			return GetRuleContext<RelationshipSourceExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationshipDestinationExprContext[] relationshipDestinationExpr() {
			return GetRuleContexts<RelationshipDestinationExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationshipDestinationExprContext relationshipDestinationExpr(int i) {
			return GetRuleContext<RelationshipDestinationExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationshipSpecifiedExprContext[] relationshipSpecifiedExpr() {
			return GetRuleContexts<RelationshipSpecifiedExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationshipSpecifiedExprContext relationshipSpecifiedExpr(int i) {
			return GetRuleContext<RelationshipSpecifiedExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationshipAllExprContext[] relationshipAllExpr() {
			return GetRuleContexts<RelationshipAllExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationshipAllExprContext relationshipAllExpr(int i) {
			return GetRuleContext<RelationshipAllExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionConnectorContext[] expressionConnector() {
			return GetRuleContexts<ExpressionConnectorContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionConnectorContext expressionConnector(int i) {
			return GetRuleContext<ExpressionConnectorContext>(i);
		}
		public GeneralExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_generalExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGeneralExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GeneralExpressionContext generalExpression() {
		GeneralExpressionContext _localctx = new GeneralExpressionContext(Context, State);
		EnterRule(_localctx, 0, RULE_generalExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 2359288L) != 0)) {
				{
				State = 51;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
				case 1:
					{
					State = 38;
					elementTypeExpr();
					}
					break;
				case 2:
					{
					State = 39;
					elementParentExpr();
					}
					break;
				case 3:
					{
					State = 40;
					elementTagExpr();
					}
					break;
				case 4:
					{
					State = 41;
					elementTechnologyExpr();
					}
					break;
				case 5:
					{
					State = 42;
					elementPropertiesExpr();
					}
					break;
				case 6:
					{
					State = 43;
					elementWithCouplingsExpr();
					}
					break;
				case 7:
					{
					State = 44;
					relationshipTagExpr();
					}
					break;
				case 8:
					{
					State = 45;
					relationshipPropertiesExpr();
					}
					break;
				case 9:
					{
					State = 46;
					relationshipSourceExpr();
					}
					break;
				case 10:
					{
					State = 47;
					relationshipDestinationExpr();
					}
					break;
				case 11:
					{
					State = 48;
					relationshipSpecifiedExpr();
					}
					break;
				case 12:
					{
					State = 49;
					relationshipAllExpr();
					}
					break;
				case 13:
					{
					State = 50;
					expressionConnector();
					}
					break;
				}
				}
				State = 55;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElementTypeExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELEMENT_TYPE() { return GetToken(StructurizrDSLExpressionsParser.ELEMENT_TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(StructurizrDSLExpressionsParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionValueContext expressionValue() {
			return GetRuleContext<ExpressionValueContext>(0);
		}
		public ElementTypeExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elementTypeExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElementTypeExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElementTypeExprContext elementTypeExpr() {
		ElementTypeExprContext _localctx = new ElementTypeExprContext(Context, State);
		EnterRule(_localctx, 2, RULE_elementTypeExpr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 56;
			Match(ELEMENT_TYPE);
			State = 57;
			Match(EQUALS);
			State = 58;
			expressionValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElementParentExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELEMENT_PARENT() { return GetToken(StructurizrDSLExpressionsParser.ELEMENT_PARENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(StructurizrDSLExpressionsParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionValueContext expressionValue() {
			return GetRuleContext<ExpressionValueContext>(0);
		}
		public ElementParentExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elementParentExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElementParentExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElementParentExprContext elementParentExpr() {
		ElementParentExprContext _localctx = new ElementParentExprContext(Context, State);
		EnterRule(_localctx, 4, RULE_elementParentExpr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 60;
			Match(ELEMENT_PARENT);
			State = 61;
			Match(EQUALS);
			State = 62;
			expressionValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElementTagExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELEMENT_TAG() { return GetToken(StructurizrDSLExpressionsParser.ELEMENT_TAG, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(StructurizrDSLExpressionsParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOTEQUALS() { return GetToken(StructurizrDSLExpressionsParser.NOTEQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionValueContext[] expressionValue() {
			return GetRuleContexts<ExpressionValueContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionValueContext expressionValue(int i) {
			return GetRuleContext<ExpressionValueContext>(i);
		}
		public ElementTagExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elementTagExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElementTagExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElementTagExprContext elementTagExpr() {
		ElementTagExprContext _localctx = new ElementTagExprContext(Context, State);
		EnterRule(_localctx, 6, RULE_elementTagExpr);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 64;
			Match(ELEMENT_TAG);
			State = 65;
			_la = TokenStream.LA(1);
			if ( !(_la==EQUALS || _la==NOTEQUALS) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 67;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 66;
					expressionValue();
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 69;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElementTechnologyExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELEMENT_TECHNOLOGY() { return GetToken(StructurizrDSLExpressionsParser.ELEMENT_TECHNOLOGY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionValueContext expressionValue() {
			return GetRuleContext<ExpressionValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(StructurizrDSLExpressionsParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOTEQUALS() { return GetToken(StructurizrDSLExpressionsParser.NOTEQUALS, 0); }
		public ElementTechnologyExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elementTechnologyExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElementTechnologyExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElementTechnologyExprContext elementTechnologyExpr() {
		ElementTechnologyExprContext _localctx = new ElementTechnologyExprContext(Context, State);
		EnterRule(_localctx, 8, RULE_elementTechnologyExpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 71;
			Match(ELEMENT_TECHNOLOGY);
			State = 72;
			_la = TokenStream.LA(1);
			if ( !(_la==EQUALS || _la==NOTEQUALS) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 73;
			expressionValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElementPropertiesExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELEMENT_PROPERTIES() { return GetToken(StructurizrDSLExpressionsParser.ELEMENT_PROPERTIES, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PropertyNameContext propertyName() {
			return GetRuleContext<PropertyNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionValueContext expressionValue() {
			return GetRuleContext<ExpressionValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(StructurizrDSLExpressionsParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOTEQUALS() { return GetToken(StructurizrDSLExpressionsParser.NOTEQUALS, 0); }
		public ElementPropertiesExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elementPropertiesExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElementPropertiesExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElementPropertiesExprContext elementPropertiesExpr() {
		ElementPropertiesExprContext _localctx = new ElementPropertiesExprContext(Context, State);
		EnterRule(_localctx, 10, RULE_elementPropertiesExpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 75;
			Match(ELEMENT_PROPERTIES);
			State = 76;
			Match(T__0);
			State = 77;
			propertyName();
			State = 78;
			Match(T__1);
			State = 79;
			_la = TokenStream.LA(1);
			if ( !(_la==EQUALS || _la==NOTEQUALS) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 80;
			expressionValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElementWithCouplingsExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELEMENT() { return GetToken(StructurizrDSLExpressionsParser.ELEMENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(StructurizrDSLExpressionsParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionValueContext expressionValue() {
			return GetRuleContext<ExpressionValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationshipPointerContext[] relationshipPointer() {
			return GetRuleContexts<RelationshipPointerContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationshipPointerContext relationshipPointer(int i) {
			return GetRuleContext<RelationshipPointerContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MORE_THAN() { return GetToken(StructurizrDSLExpressionsParser.MORE_THAN, 0); }
		public ElementWithCouplingsExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elementWithCouplingsExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElementWithCouplingsExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElementWithCouplingsExprContext elementWithCouplingsExpr() {
		ElementWithCouplingsExprContext _localctx = new ElementWithCouplingsExprContext(Context, State);
		EnterRule(_localctx, 12, RULE_elementWithCouplingsExpr);
		int _la;
		try {
			State = 104;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ELEMENT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 82;
				Match(ELEMENT);
				State = 83;
				Match(EQUALS);
				State = 85;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==RELATIONSHIP_POINTER) {
					{
					State = 84;
					relationshipPointer();
					}
				}

				State = 87;
				expressionValue();
				State = 89;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
				case 1:
					{
					State = 88;
					relationshipPointer();
					}
					break;
				}
				State = 92;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==MORE_THAN) {
					{
					State = 91;
					Match(MORE_THAN);
					}
				}

				}
				break;
			case VALUE:
			case RELATIONSHIP_POINTER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 95;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==RELATIONSHIP_POINTER) {
					{
					State = 94;
					relationshipPointer();
					}
				}

				State = 97;
				expressionValue();
				State = 99;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
				case 1:
					{
					State = 98;
					relationshipPointer();
					}
					break;
				}
				State = 102;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==MORE_THAN) {
					{
					State = 101;
					Match(MORE_THAN);
					}
				}

				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationshipTagExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RELATIONSHIP_TAG() { return GetToken(StructurizrDSLExpressionsParser.RELATIONSHIP_TAG, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(StructurizrDSLExpressionsParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOTEQUALS() { return GetToken(StructurizrDSLExpressionsParser.NOTEQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionValueContext[] expressionValue() {
			return GetRuleContexts<ExpressionValueContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionValueContext expressionValue(int i) {
			return GetRuleContext<ExpressionValueContext>(i);
		}
		public RelationshipTagExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationshipTagExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationshipTagExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationshipTagExprContext relationshipTagExpr() {
		RelationshipTagExprContext _localctx = new RelationshipTagExprContext(Context, State);
		EnterRule(_localctx, 14, RULE_relationshipTagExpr);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 106;
			Match(RELATIONSHIP_TAG);
			State = 107;
			_la = TokenStream.LA(1);
			if ( !(_la==EQUALS || _la==NOTEQUALS) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 109;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 108;
					expressionValue();
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 111;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationshipPropertiesExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RELATIONSHIP_PROPERTIES() { return GetToken(StructurizrDSLExpressionsParser.RELATIONSHIP_PROPERTIES, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PropertyNameContext propertyName() {
			return GetRuleContext<PropertyNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionValueContext expressionValue() {
			return GetRuleContext<ExpressionValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(StructurizrDSLExpressionsParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOTEQUALS() { return GetToken(StructurizrDSLExpressionsParser.NOTEQUALS, 0); }
		public RelationshipPropertiesExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationshipPropertiesExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationshipPropertiesExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationshipPropertiesExprContext relationshipPropertiesExpr() {
		RelationshipPropertiesExprContext _localctx = new RelationshipPropertiesExprContext(Context, State);
		EnterRule(_localctx, 16, RULE_relationshipPropertiesExpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 113;
			Match(RELATIONSHIP_PROPERTIES);
			State = 114;
			Match(T__0);
			State = 115;
			propertyName();
			State = 116;
			Match(T__1);
			State = 117;
			_la = TokenStream.LA(1);
			if ( !(_la==EQUALS || _la==NOTEQUALS) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 118;
			expressionValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationshipSourceExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RELATIONSHIP_SOURCE() { return GetToken(StructurizrDSLExpressionsParser.RELATIONSHIP_SOURCE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(StructurizrDSLExpressionsParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionValueContext expressionValue() {
			return GetRuleContext<ExpressionValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RELATIONSHIP() { return GetToken(StructurizrDSLExpressionsParser.RELATIONSHIP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WILDCARD() { return GetToken(StructurizrDSLExpressionsParser.WILDCARD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RELATIONSHIP_POINTER() { return GetToken(StructurizrDSLExpressionsParser.RELATIONSHIP_POINTER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MORE_THAN() { return GetToken(StructurizrDSLExpressionsParser.MORE_THAN, 0); }
		public RelationshipSourceExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationshipSourceExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationshipSourceExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationshipSourceExprContext relationshipSourceExpr() {
		RelationshipSourceExprContext _localctx = new RelationshipSourceExprContext(Context, State);
		EnterRule(_localctx, 18, RULE_relationshipSourceExpr);
		int _la;
		try {
			State = 143;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case RELATIONSHIP_SOURCE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 120;
				Match(RELATIONSHIP_SOURCE);
				State = 121;
				Match(EQUALS);
				State = 122;
				expressionValue();
				}
				break;
			case RELATIONSHIP:
				EnterOuterAlt(_localctx, 2);
				{
				State = 123;
				Match(RELATIONSHIP);
				State = 124;
				Match(EQUALS);
				State = 125;
				expressionValue();
				State = 127;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==RELATIONSHIP_POINTER) {
					{
					State = 126;
					Match(RELATIONSHIP_POINTER);
					}
				}

				State = 130;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==MORE_THAN) {
					{
					State = 129;
					Match(MORE_THAN);
					}
				}

				State = 132;
				Match(WILDCARD);
				}
				break;
			case VALUE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 134;
				expressionValue();
				State = 136;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==RELATIONSHIP_POINTER) {
					{
					State = 135;
					Match(RELATIONSHIP_POINTER);
					}
				}

				State = 139;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==MORE_THAN) {
					{
					State = 138;
					Match(MORE_THAN);
					}
				}

				State = 141;
				Match(WILDCARD);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationshipDestinationExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RELATIONSHIP_DESTINATION() { return GetToken(StructurizrDSLExpressionsParser.RELATIONSHIP_DESTINATION, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(StructurizrDSLExpressionsParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionValueContext expressionValue() {
			return GetRuleContext<ExpressionValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WILDCARD() { return GetToken(StructurizrDSLExpressionsParser.WILDCARD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RELATIONSHIP_POINTER() { return GetToken(StructurizrDSLExpressionsParser.RELATIONSHIP_POINTER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RELATIONSHIP() { return GetToken(StructurizrDSLExpressionsParser.RELATIONSHIP, 0); }
		public RelationshipDestinationExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationshipDestinationExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationshipDestinationExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationshipDestinationExprContext relationshipDestinationExpr() {
		RelationshipDestinationExprContext _localctx = new RelationshipDestinationExprContext(Context, State);
		EnterRule(_localctx, 20, RULE_relationshipDestinationExpr);
		try {
			State = 156;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case RELATIONSHIP_DESTINATION:
				EnterOuterAlt(_localctx, 1);
				{
				State = 145;
				Match(RELATIONSHIP_DESTINATION);
				State = 146;
				Match(EQUALS);
				State = 147;
				expressionValue();
				}
				break;
			case WILDCARD:
				EnterOuterAlt(_localctx, 2);
				{
				State = 148;
				Match(WILDCARD);
				State = 149;
				Match(RELATIONSHIP_POINTER);
				State = 150;
				expressionValue();
				}
				break;
			case RELATIONSHIP:
				EnterOuterAlt(_localctx, 3);
				{
				State = 151;
				Match(RELATIONSHIP);
				State = 152;
				Match(EQUALS);
				State = 153;
				Match(WILDCARD);
				State = 154;
				Match(RELATIONSHIP_POINTER);
				State = 155;
				expressionValue();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationshipSpecifiedExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RELATIONSHIP() { return GetToken(StructurizrDSLExpressionsParser.RELATIONSHIP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(StructurizrDSLExpressionsParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SourceElementContext sourceElement() {
			return GetRuleContext<SourceElementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DestinationElementContext destinationElement() {
			return GetRuleContext<DestinationElementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RELATIONSHIP_POINTER() { return GetToken(StructurizrDSLExpressionsParser.RELATIONSHIP_POINTER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MORE_THAN() { return GetToken(StructurizrDSLExpressionsParser.MORE_THAN, 0); }
		public RelationshipSpecifiedExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationshipSpecifiedExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationshipSpecifiedExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationshipSpecifiedExprContext relationshipSpecifiedExpr() {
		RelationshipSpecifiedExprContext _localctx = new RelationshipSpecifiedExprContext(Context, State);
		EnterRule(_localctx, 22, RULE_relationshipSpecifiedExpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 158;
			Match(RELATIONSHIP);
			State = 159;
			Match(EQUALS);
			State = 160;
			sourceElement();
			State = 162;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==RELATIONSHIP_POINTER) {
				{
				State = 161;
				Match(RELATIONSHIP_POINTER);
				}
			}

			State = 165;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==MORE_THAN) {
				{
				State = 164;
				Match(MORE_THAN);
				}
			}

			State = 167;
			destinationElement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationshipAllExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] WILDCARD() { return GetTokens(StructurizrDSLExpressionsParser.WILDCARD); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WILDCARD(int i) {
			return GetToken(StructurizrDSLExpressionsParser.WILDCARD, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RELATIONSHIP_POINTER() { return GetToken(StructurizrDSLExpressionsParser.RELATIONSHIP_POINTER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RELATIONSHIP() { return GetToken(StructurizrDSLExpressionsParser.RELATIONSHIP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(StructurizrDSLExpressionsParser.EQUALS, 0); }
		public RelationshipAllExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationshipAllExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationshipAllExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationshipAllExprContext relationshipAllExpr() {
		RelationshipAllExprContext _localctx = new RelationshipAllExprContext(Context, State);
		EnterRule(_localctx, 24, RULE_relationshipAllExpr);
		try {
			State = 180;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 169;
				Match(WILDCARD);
				State = 170;
				Match(RELATIONSHIP_POINTER);
				State = 171;
				Match(WILDCARD);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 172;
				Match(RELATIONSHIP);
				State = 173;
				Match(EQUALS);
				State = 174;
				Match(WILDCARD);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 175;
				Match(RELATIONSHIP);
				State = 176;
				Match(EQUALS);
				State = 177;
				Match(WILDCARD);
				State = 178;
				Match(RELATIONSHIP_POINTER);
				State = 179;
				Match(WILDCARD);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SourceElementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VALUE() { return GetToken(StructurizrDSLExpressionsParser.VALUE, 0); }
		public SourceElementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sourceElement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSourceElement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SourceElementContext sourceElement() {
		SourceElementContext _localctx = new SourceElementContext(Context, State);
		EnterRule(_localctx, 26, RULE_sourceElement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 182;
			Match(VALUE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DestinationElementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VALUE() { return GetToken(StructurizrDSLExpressionsParser.VALUE, 0); }
		public DestinationElementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_destinationElement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDestinationElement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DestinationElementContext destinationElement() {
		DestinationElementContext _localctx = new DestinationElementContext(Context, State);
		EnterRule(_localctx, 28, RULE_destinationElement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 184;
			Match(VALUE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationshipPointerContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RELATIONSHIP_POINTER() { return GetToken(StructurizrDSLExpressionsParser.RELATIONSHIP_POINTER, 0); }
		public RelationshipPointerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationshipPointer; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationshipPointer(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationshipPointerContext relationshipPointer() {
		RelationshipPointerContext _localctx = new RelationshipPointerContext(Context, State);
		EnterRule(_localctx, 30, RULE_relationshipPointer);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 186;
			Match(RELATIONSHIP_POINTER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VALUE() { return GetToken(StructurizrDSLExpressionsParser.VALUE, 0); }
		public ExpressionValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expressionValue; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionValueContext expressionValue() {
		ExpressionValueContext _localctx = new ExpressionValueContext(Context, State);
		EnterRule(_localctx, 32, RULE_expressionValue);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 188;
			Match(VALUE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropertyNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VALUE() { return GetToken(StructurizrDSLExpressionsParser.VALUE, 0); }
		public PropertyNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_propertyName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPropertyName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PropertyNameContext propertyName() {
		PropertyNameContext _localctx = new PropertyNameContext(Context, State);
		EnterRule(_localctx, 34, RULE_propertyName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 190;
			Match(VALUE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionConnectorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND() { return GetToken(StructurizrDSLExpressionsParser.AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR() { return GetToken(StructurizrDSLExpressionsParser.OR, 0); }
		public ExpressionConnectorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expressionConnector; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStructurizrDSLExpressionsVisitor<TResult> typedVisitor = visitor as IStructurizrDSLExpressionsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionConnector(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionConnectorContext expressionConnector() {
		ExpressionConnectorContext _localctx = new ExpressionConnectorContext(Context, State);
		EnterRule(_localctx, 36, RULE_expressionConnector);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 192;
			_la = TokenStream.LA(1);
			if ( !(_la==OR || _la==AND) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,23,195,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,
		0,1,0,1,0,1,0,1,0,1,0,5,0,52,8,0,10,0,12,0,55,9,0,1,1,1,1,1,1,1,1,1,2,
		1,2,1,2,1,2,1,3,1,3,1,3,4,3,68,8,3,11,3,12,3,69,1,4,1,4,1,4,1,4,1,5,1,
		5,1,5,1,5,1,5,1,5,1,5,1,6,1,6,1,6,3,6,86,8,6,1,6,1,6,3,6,90,8,6,1,6,3,
		6,93,8,6,1,6,3,6,96,8,6,1,6,1,6,3,6,100,8,6,1,6,3,6,103,8,6,3,6,105,8,
		6,1,7,1,7,1,7,4,7,110,8,7,11,7,12,7,111,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,
		9,1,9,1,9,1,9,1,9,1,9,1,9,3,9,128,8,9,1,9,3,9,131,8,9,1,9,1,9,1,9,1,9,
		3,9,137,8,9,1,9,3,9,140,8,9,1,9,1,9,3,9,144,8,9,1,10,1,10,1,10,1,10,1,
		10,1,10,1,10,1,10,1,10,1,10,1,10,3,10,157,8,10,1,11,1,11,1,11,1,11,3,11,
		163,8,11,1,11,3,11,166,8,11,1,11,1,11,1,12,1,12,1,12,1,12,1,12,1,12,1,
		12,1,12,1,12,1,12,1,12,3,12,181,8,12,1,13,1,13,1,14,1,14,1,15,1,15,1,16,
		1,16,1,17,1,17,1,18,1,18,1,18,0,0,19,0,2,4,6,8,10,12,14,16,18,20,22,24,
		26,28,30,32,34,36,0,2,1,0,19,20,1,0,15,16,209,0,53,1,0,0,0,2,56,1,0,0,
		0,4,60,1,0,0,0,6,64,1,0,0,0,8,71,1,0,0,0,10,75,1,0,0,0,12,104,1,0,0,0,
		14,106,1,0,0,0,16,113,1,0,0,0,18,143,1,0,0,0,20,156,1,0,0,0,22,158,1,0,
		0,0,24,180,1,0,0,0,26,182,1,0,0,0,28,184,1,0,0,0,30,186,1,0,0,0,32,188,
		1,0,0,0,34,190,1,0,0,0,36,192,1,0,0,0,38,52,3,2,1,0,39,52,3,4,2,0,40,52,
		3,6,3,0,41,52,3,8,4,0,42,52,3,10,5,0,43,52,3,12,6,0,44,52,3,14,7,0,45,
		52,3,16,8,0,46,52,3,18,9,0,47,52,3,20,10,0,48,52,3,22,11,0,49,52,3,24,
		12,0,50,52,3,36,18,0,51,38,1,0,0,0,51,39,1,0,0,0,51,40,1,0,0,0,51,41,1,
		0,0,0,51,42,1,0,0,0,51,43,1,0,0,0,51,44,1,0,0,0,51,45,1,0,0,0,51,46,1,
		0,0,0,51,47,1,0,0,0,51,48,1,0,0,0,51,49,1,0,0,0,51,50,1,0,0,0,52,55,1,
		0,0,0,53,51,1,0,0,0,53,54,1,0,0,0,54,1,1,0,0,0,55,53,1,0,0,0,56,57,5,4,
		0,0,57,58,5,19,0,0,58,59,3,32,16,0,59,3,1,0,0,0,60,61,5,5,0,0,61,62,5,
		19,0,0,62,63,3,32,16,0,63,5,1,0,0,0,64,65,5,6,0,0,65,67,7,0,0,0,66,68,
		3,32,16,0,67,66,1,0,0,0,68,69,1,0,0,0,69,67,1,0,0,0,69,70,1,0,0,0,70,7,
		1,0,0,0,71,72,5,7,0,0,72,73,7,0,0,0,73,74,3,32,16,0,74,9,1,0,0,0,75,76,
		5,8,0,0,76,77,5,1,0,0,77,78,3,34,17,0,78,79,5,2,0,0,79,80,7,0,0,0,80,81,
		3,32,16,0,81,11,1,0,0,0,82,83,5,3,0,0,83,85,5,19,0,0,84,86,3,30,15,0,85,
		84,1,0,0,0,85,86,1,0,0,0,86,87,1,0,0,0,87,89,3,32,16,0,88,90,3,30,15,0,
		89,88,1,0,0,0,89,90,1,0,0,0,90,92,1,0,0,0,91,93,5,22,0,0,92,91,1,0,0,0,
		92,93,1,0,0,0,93,105,1,0,0,0,94,96,3,30,15,0,95,94,1,0,0,0,95,96,1,0,0,
		0,96,97,1,0,0,0,97,99,3,32,16,0,98,100,3,30,15,0,99,98,1,0,0,0,99,100,
		1,0,0,0,100,102,1,0,0,0,101,103,5,22,0,0,102,101,1,0,0,0,102,103,1,0,0,
		0,103,105,1,0,0,0,104,82,1,0,0,0,104,95,1,0,0,0,105,13,1,0,0,0,106,107,
		5,10,0,0,107,109,7,0,0,0,108,110,3,32,16,0,109,108,1,0,0,0,110,111,1,0,
		0,0,111,109,1,0,0,0,111,112,1,0,0,0,112,15,1,0,0,0,113,114,5,11,0,0,114,
		115,5,1,0,0,115,116,3,34,17,0,116,117,5,2,0,0,117,118,7,0,0,0,118,119,
		3,32,16,0,119,17,1,0,0,0,120,121,5,12,0,0,121,122,5,19,0,0,122,144,3,32,
		16,0,123,124,5,9,0,0,124,125,5,19,0,0,125,127,3,32,16,0,126,128,5,21,0,
		0,127,126,1,0,0,0,127,128,1,0,0,0,128,130,1,0,0,0,129,131,5,22,0,0,130,
		129,1,0,0,0,130,131,1,0,0,0,131,132,1,0,0,0,132,133,5,17,0,0,133,144,1,
		0,0,0,134,136,3,32,16,0,135,137,5,21,0,0,136,135,1,0,0,0,136,137,1,0,0,
		0,137,139,1,0,0,0,138,140,5,22,0,0,139,138,1,0,0,0,139,140,1,0,0,0,140,
		141,1,0,0,0,141,142,5,17,0,0,142,144,1,0,0,0,143,120,1,0,0,0,143,123,1,
		0,0,0,143,134,1,0,0,0,144,19,1,0,0,0,145,146,5,13,0,0,146,147,5,19,0,0,
		147,157,3,32,16,0,148,149,5,17,0,0,149,150,5,21,0,0,150,157,3,32,16,0,
		151,152,5,9,0,0,152,153,5,19,0,0,153,154,5,17,0,0,154,155,5,21,0,0,155,
		157,3,32,16,0,156,145,1,0,0,0,156,148,1,0,0,0,156,151,1,0,0,0,157,21,1,
		0,0,0,158,159,5,9,0,0,159,160,5,19,0,0,160,162,3,26,13,0,161,163,5,21,
		0,0,162,161,1,0,0,0,162,163,1,0,0,0,163,165,1,0,0,0,164,166,5,22,0,0,165,
		164,1,0,0,0,165,166,1,0,0,0,166,167,1,0,0,0,167,168,3,28,14,0,168,23,1,
		0,0,0,169,170,5,17,0,0,170,171,5,21,0,0,171,181,5,17,0,0,172,173,5,9,0,
		0,173,174,5,19,0,0,174,181,5,17,0,0,175,176,5,9,0,0,176,177,5,19,0,0,177,
		178,5,17,0,0,178,179,5,21,0,0,179,181,5,17,0,0,180,169,1,0,0,0,180,172,
		1,0,0,0,180,175,1,0,0,0,181,25,1,0,0,0,182,183,5,14,0,0,183,27,1,0,0,0,
		184,185,5,14,0,0,185,29,1,0,0,0,186,187,5,21,0,0,187,31,1,0,0,0,188,189,
		5,14,0,0,189,33,1,0,0,0,190,191,5,14,0,0,191,35,1,0,0,0,192,193,7,1,0,
		0,193,37,1,0,0,0,20,51,53,69,85,89,92,95,99,102,104,111,127,130,136,139,
		143,156,162,165,180
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
