/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { type DocumentationContent } from '../models';
/**
 * DocumentationsApi - axios parameter creator
 * @export
 */
export const DocumentationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} documentationId 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesWorkspaceIdDocumentationsDocumentationIdImagesNameGet: async (workspaceId: string, documentationId: string, name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('apiWorkspacesWorkspaceIdDocumentationsDocumentationIdImagesNameGet', 'workspaceId', workspaceId)
            // verify required parameter 'documentationId' is not null or undefined
            assertParamExists('apiWorkspacesWorkspaceIdDocumentationsDocumentationIdImagesNameGet', 'documentationId', documentationId)
            // verify required parameter 'name' is not null or undefined
            assertParamExists('apiWorkspacesWorkspaceIdDocumentationsDocumentationIdImagesNameGet', 'name', name)
            const localVarPath = `/api/workspaces/{workspaceId}/documentations/{documentationId}/images/{name}`
                .replace(`{${"workspaceId"}}`, encodeURIComponent(String(workspaceId)))
                .replace(`{${"documentationId"}}`, encodeURIComponent(String(documentationId)))
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} elementId 
         * @param {string} [baseUrl] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesWorkspaceIdDocumentationsElementElementIdGet: async (workspaceId: string, elementId: string, baseUrl?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('apiWorkspacesWorkspaceIdDocumentationsElementElementIdGet', 'workspaceId', workspaceId)
            // verify required parameter 'elementId' is not null or undefined
            assertParamExists('apiWorkspacesWorkspaceIdDocumentationsElementElementIdGet', 'elementId', elementId)
            const localVarPath = `/api/workspaces/{workspaceId}/documentations/element/{elementId}`
                .replace(`{${"workspaceId"}}`, encodeURIComponent(String(workspaceId)))
                .replace(`{${"elementId"}}`, encodeURIComponent(String(elementId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (baseUrl !== undefined) {
                localVarQueryParameter['baseUrl'] = baseUrl;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} [baseUrl] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesWorkspaceIdDocumentationsWorskpaceGet: async (workspaceId: string, baseUrl?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('apiWorkspacesWorkspaceIdDocumentationsWorskpaceGet', 'workspaceId', workspaceId)
            const localVarPath = `/api/workspaces/{workspaceId}/documentations/worskpace`
                .replace(`{${"workspaceId"}}`, encodeURIComponent(String(workspaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (baseUrl !== undefined) {
                localVarQueryParameter['baseUrl'] = baseUrl;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DocumentationsApi - functional programming interface
 * @export
 */
export const DocumentationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DocumentationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} documentationId 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesWorkspaceIdDocumentationsDocumentationIdImagesNameGet(workspaceId: string, documentationId: string, name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesWorkspaceIdDocumentationsDocumentationIdImagesNameGet(workspaceId, documentationId, name, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DocumentationsApi.apiWorkspacesWorkspaceIdDocumentationsDocumentationIdImagesNameGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} elementId 
         * @param {string} [baseUrl] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesWorkspaceIdDocumentationsElementElementIdGet(workspaceId: string, elementId: string, baseUrl?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DocumentationContent>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesWorkspaceIdDocumentationsElementElementIdGet(workspaceId, elementId, baseUrl, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DocumentationsApi.apiWorkspacesWorkspaceIdDocumentationsElementElementIdGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} [baseUrl] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesWorkspaceIdDocumentationsWorskpaceGet(workspaceId: string, baseUrl?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DocumentationContent>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesWorkspaceIdDocumentationsWorskpaceGet(workspaceId, baseUrl, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DocumentationsApi.apiWorkspacesWorkspaceIdDocumentationsWorskpaceGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * DocumentationsApi - factory interface
 * @export
 */
export const DocumentationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DocumentationsApiFp(configuration)
    return {
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} documentationId 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesWorkspaceIdDocumentationsDocumentationIdImagesNameGet(workspaceId: string, documentationId: string, name: string, options?: any): AxiosPromise<void> {
            return localVarFp.apiWorkspacesWorkspaceIdDocumentationsDocumentationIdImagesNameGet(workspaceId, documentationId, name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} elementId 
         * @param {string} [baseUrl] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesWorkspaceIdDocumentationsElementElementIdGet(workspaceId: string, elementId: string, baseUrl?: string, options?: any): AxiosPromise<DocumentationContent> {
            return localVarFp.apiWorkspacesWorkspaceIdDocumentationsElementElementIdGet(workspaceId, elementId, baseUrl, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} [baseUrl] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesWorkspaceIdDocumentationsWorskpaceGet(workspaceId: string, baseUrl?: string, options?: any): AxiosPromise<DocumentationContent> {
            return localVarFp.apiWorkspacesWorkspaceIdDocumentationsWorskpaceGet(workspaceId, baseUrl, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DocumentationsApi - object-oriented interface
 * @export
 * @class DocumentationsApi
 * @extends {BaseAPI}
 */
export class DocumentationsApi extends BaseAPI {
    /**
     * 
     * @param {string} workspaceId 
     * @param {string} documentationId 
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentationsApi
     */
    public apiWorkspacesWorkspaceIdDocumentationsDocumentationIdImagesNameGet(workspaceId: string, documentationId: string, name: string, options?: RawAxiosRequestConfig) {
        return DocumentationsApiFp(this.configuration).apiWorkspacesWorkspaceIdDocumentationsDocumentationIdImagesNameGet(workspaceId, documentationId, name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {string} elementId 
     * @param {string} [baseUrl] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentationsApi
     */
    public apiWorkspacesWorkspaceIdDocumentationsElementElementIdGet(workspaceId: string, elementId: string, baseUrl?: string, options?: RawAxiosRequestConfig) {
        return DocumentationsApiFp(this.configuration).apiWorkspacesWorkspaceIdDocumentationsElementElementIdGet(workspaceId, elementId, baseUrl, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {string} [baseUrl] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentationsApi
     */
    public apiWorkspacesWorkspaceIdDocumentationsWorskpaceGet(workspaceId: string, baseUrl?: string, options?: RawAxiosRequestConfig) {
        return DocumentationsApiFp(this.configuration).apiWorkspacesWorkspaceIdDocumentationsWorskpaceGet(workspaceId, baseUrl, options).then((request) => request(this.axios, this.basePath));
    }
}

