/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ImportOpenApiFileRequest } from '../models';
/**
 * DocumentationFilesImportApi - axios parameter creator
 */
export const DocumentationFilesImportApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} [elementId] 
         * @param {string} [elementDslId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesWorkspaceIdDocfileOpenapiDelete: async (workspaceId: string, elementId?: string, elementDslId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('apiWorkspacesWorkspaceIdDocfileOpenapiDelete', 'workspaceId', workspaceId)
            const localVarPath = `/api/workspaces/{workspaceId}/docfile/openapi`
                .replace(`{${"workspaceId"}}`, encodeURIComponent(String(workspaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (elementId !== undefined) {
                localVarQueryParameter['elementId'] = elementId;
            }

            if (elementDslId !== undefined) {
                localVarQueryParameter['elementDslId'] = elementDslId;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {ImportOpenApiFileRequest} [importOpenApiFileRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesWorkspaceIdDocfileOpenapiPut: async (workspaceId: string, importOpenApiFileRequest?: ImportOpenApiFileRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workspaceId' is not null or undefined
            assertParamExists('apiWorkspacesWorkspaceIdDocfileOpenapiPut', 'workspaceId', workspaceId)
            const localVarPath = `/api/workspaces/{workspaceId}/docfile/openapi`
                .replace(`{${"workspaceId"}}`, encodeURIComponent(String(workspaceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(importOpenApiFileRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DocumentationFilesImportApi - functional programming interface
 */
export const DocumentationFilesImportApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DocumentationFilesImportApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} [elementId] 
         * @param {string} [elementDslId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesWorkspaceIdDocfileOpenapiDelete(workspaceId: string, elementId?: string, elementDslId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesWorkspaceIdDocfileOpenapiDelete(workspaceId, elementId, elementDslId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DocumentationFilesImportApi.apiWorkspacesWorkspaceIdDocfileOpenapiDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {ImportOpenApiFileRequest} [importOpenApiFileRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesWorkspaceIdDocfileOpenapiPut(workspaceId: string, importOpenApiFileRequest?: ImportOpenApiFileRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesWorkspaceIdDocfileOpenapiPut(workspaceId, importOpenApiFileRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DocumentationFilesImportApi.apiWorkspacesWorkspaceIdDocfileOpenapiPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DocumentationFilesImportApi - factory interface
 */
export const DocumentationFilesImportApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DocumentationFilesImportApiFp(configuration)
    return {
        /**
         * 
         * @param {string} workspaceId 
         * @param {string} [elementId] 
         * @param {string} [elementDslId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesWorkspaceIdDocfileOpenapiDelete(workspaceId: string, elementId?: string, elementDslId?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiWorkspacesWorkspaceIdDocfileOpenapiDelete(workspaceId, elementId, elementDslId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} workspaceId 
         * @param {ImportOpenApiFileRequest} [importOpenApiFileRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesWorkspaceIdDocfileOpenapiPut(workspaceId: string, importOpenApiFileRequest?: ImportOpenApiFileRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiWorkspacesWorkspaceIdDocfileOpenapiPut(workspaceId, importOpenApiFileRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DocumentationFilesImportApi - object-oriented interface
 */
export class DocumentationFilesImportApi extends BaseAPI {
    /**
     * 
     * @param {string} workspaceId 
     * @param {string} [elementId] 
     * @param {string} [elementDslId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiWorkspacesWorkspaceIdDocfileOpenapiDelete(workspaceId: string, elementId?: string, elementDslId?: string, options?: RawAxiosRequestConfig) {
        return DocumentationFilesImportApiFp(this.configuration).apiWorkspacesWorkspaceIdDocfileOpenapiDelete(workspaceId, elementId, elementDslId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} workspaceId 
     * @param {ImportOpenApiFileRequest} [importOpenApiFileRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiWorkspacesWorkspaceIdDocfileOpenapiPut(workspaceId: string, importOpenApiFileRequest?: ImportOpenApiFileRequest, options?: RawAxiosRequestConfig) {
        return DocumentationFilesImportApiFp(this.configuration).apiWorkspacesWorkspaceIdDocfileOpenapiPut(workspaceId, importOpenApiFileRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

