/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ImportClearDecisionsRequest } from '../models';
// @ts-ignore
import type { ImportClearDocItemsRequest } from '../models';
// @ts-ignore
import type { ImportDecisionRequest } from '../models';
// @ts-ignore
import type { ImportDecisionsLinksRequest } from '../models';
// @ts-ignore
import type { ImportDocumentationRequest } from '../models';
// @ts-ignore
import type { ImportElementsRequest } from '../models';
// @ts-ignore
import type { ImportFinalizeRequest } from '../models';
// @ts-ignore
import type { ImportImageRequest } from '../models';
// @ts-ignore
import type { ImportRelationshipsRequest } from '../models';
// @ts-ignore
import type { ImportViewConfigurationRequest } from '../models';
// @ts-ignore
import type { ImportViewsRequest } from '../models';
// @ts-ignore
import type { ImportWorkspaceResponse } from '../models';
// @ts-ignore
import type { ImportWorkspaceStartRequest } from '../models';
/**
 * WorkspacesImportApi - axios parameter creator
 */
export const WorkspacesImportApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ImportClearDecisionsRequest} [importClearDecisionsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportCleardecisionsPut: async (importClearDecisionsRequest?: ImportClearDecisionsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/workspaces/import/cleardecisions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(importClearDecisionsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ImportClearDocItemsRequest} [importClearDocItemsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportCleardocitemsPost: async (importClearDocItemsRequest?: ImportClearDocItemsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/workspaces/import/cleardocitems`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(importClearDocItemsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ImportDecisionRequest} [importDecisionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportDecisionPut: async (importDecisionRequest?: ImportDecisionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/workspaces/import/decision`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(importDecisionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ImportDecisionsLinksRequest} [importDecisionsLinksRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportDecisionlinksPut: async (importDecisionsLinksRequest?: ImportDecisionsLinksRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/workspaces/import/decisionlinks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(importDecisionsLinksRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ImportDocumentationRequest} [importDocumentationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportDocumentationPut: async (importDocumentationRequest?: ImportDocumentationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/workspaces/import/documentation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(importDocumentationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ImportElementsRequest} [importElementsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportElementsPut: async (importElementsRequest?: ImportElementsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/workspaces/import/elements`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(importElementsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ImportFinalizeRequest} [importFinalizeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportFinishPut: async (importFinalizeRequest?: ImportFinalizeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/workspaces/import/finish`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(importFinalizeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ImportImageRequest} [importImageRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportImagePut: async (importImageRequest?: ImportImageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/workspaces/import/image`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(importImageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ImportRelationshipsRequest} [importRelationshipsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportRelationshipsPut: async (importRelationshipsRequest?: ImportRelationshipsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/workspaces/import/relationships`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(importRelationshipsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ImportWorkspaceStartRequest} [importWorkspaceStartRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportStartPut: async (importWorkspaceStartRequest?: ImportWorkspaceStartRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/workspaces/import/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(importWorkspaceStartRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ImportViewConfigurationRequest} [importViewConfigurationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportViewconfigurationPut: async (importViewConfigurationRequest?: ImportViewConfigurationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/workspaces/import/viewconfiguration`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(importViewConfigurationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ImportViewsRequest} [importViewsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportViewsPut: async (importViewsRequest?: ImportViewsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/workspaces/import/views`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(importViewsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WorkspacesImportApi - functional programming interface
 */
export const WorkspacesImportApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WorkspacesImportApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ImportClearDecisionsRequest} [importClearDecisionsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesImportCleardecisionsPut(importClearDecisionsRequest?: ImportClearDecisionsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportWorkspaceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesImportCleardecisionsPut(importClearDecisionsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkspacesImportApi.apiWorkspacesImportCleardecisionsPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ImportClearDocItemsRequest} [importClearDocItemsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesImportCleardocitemsPost(importClearDocItemsRequest?: ImportClearDocItemsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportWorkspaceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesImportCleardocitemsPost(importClearDocItemsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkspacesImportApi.apiWorkspacesImportCleardocitemsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ImportDecisionRequest} [importDecisionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesImportDecisionPut(importDecisionRequest?: ImportDecisionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportWorkspaceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesImportDecisionPut(importDecisionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkspacesImportApi.apiWorkspacesImportDecisionPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ImportDecisionsLinksRequest} [importDecisionsLinksRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesImportDecisionlinksPut(importDecisionsLinksRequest?: ImportDecisionsLinksRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportWorkspaceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesImportDecisionlinksPut(importDecisionsLinksRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkspacesImportApi.apiWorkspacesImportDecisionlinksPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ImportDocumentationRequest} [importDocumentationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesImportDocumentationPut(importDocumentationRequest?: ImportDocumentationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportWorkspaceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesImportDocumentationPut(importDocumentationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkspacesImportApi.apiWorkspacesImportDocumentationPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ImportElementsRequest} [importElementsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesImportElementsPut(importElementsRequest?: ImportElementsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportWorkspaceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesImportElementsPut(importElementsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkspacesImportApi.apiWorkspacesImportElementsPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ImportFinalizeRequest} [importFinalizeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesImportFinishPut(importFinalizeRequest?: ImportFinalizeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportWorkspaceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesImportFinishPut(importFinalizeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkspacesImportApi.apiWorkspacesImportFinishPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ImportImageRequest} [importImageRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesImportImagePut(importImageRequest?: ImportImageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportWorkspaceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesImportImagePut(importImageRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkspacesImportApi.apiWorkspacesImportImagePut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ImportRelationshipsRequest} [importRelationshipsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesImportRelationshipsPut(importRelationshipsRequest?: ImportRelationshipsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportWorkspaceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesImportRelationshipsPut(importRelationshipsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkspacesImportApi.apiWorkspacesImportRelationshipsPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ImportWorkspaceStartRequest} [importWorkspaceStartRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesImportStartPut(importWorkspaceStartRequest?: ImportWorkspaceStartRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportWorkspaceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesImportStartPut(importWorkspaceStartRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkspacesImportApi.apiWorkspacesImportStartPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ImportViewConfigurationRequest} [importViewConfigurationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesImportViewconfigurationPut(importViewConfigurationRequest?: ImportViewConfigurationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportWorkspaceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesImportViewconfigurationPut(importViewConfigurationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkspacesImportApi.apiWorkspacesImportViewconfigurationPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ImportViewsRequest} [importViewsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkspacesImportViewsPut(importViewsRequest?: ImportViewsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ImportWorkspaceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWorkspacesImportViewsPut(importViewsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkspacesImportApi.apiWorkspacesImportViewsPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WorkspacesImportApi - factory interface
 */
export const WorkspacesImportApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WorkspacesImportApiFp(configuration)
    return {
        /**
         * 
         * @param {ImportClearDecisionsRequest} [importClearDecisionsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportCleardecisionsPut(importClearDecisionsRequest?: ImportClearDecisionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImportWorkspaceResponse> {
            return localVarFp.apiWorkspacesImportCleardecisionsPut(importClearDecisionsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImportClearDocItemsRequest} [importClearDocItemsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportCleardocitemsPost(importClearDocItemsRequest?: ImportClearDocItemsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImportWorkspaceResponse> {
            return localVarFp.apiWorkspacesImportCleardocitemsPost(importClearDocItemsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImportDecisionRequest} [importDecisionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportDecisionPut(importDecisionRequest?: ImportDecisionRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImportWorkspaceResponse> {
            return localVarFp.apiWorkspacesImportDecisionPut(importDecisionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImportDecisionsLinksRequest} [importDecisionsLinksRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportDecisionlinksPut(importDecisionsLinksRequest?: ImportDecisionsLinksRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImportWorkspaceResponse> {
            return localVarFp.apiWorkspacesImportDecisionlinksPut(importDecisionsLinksRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImportDocumentationRequest} [importDocumentationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportDocumentationPut(importDocumentationRequest?: ImportDocumentationRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImportWorkspaceResponse> {
            return localVarFp.apiWorkspacesImportDocumentationPut(importDocumentationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImportElementsRequest} [importElementsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportElementsPut(importElementsRequest?: ImportElementsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImportWorkspaceResponse> {
            return localVarFp.apiWorkspacesImportElementsPut(importElementsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImportFinalizeRequest} [importFinalizeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportFinishPut(importFinalizeRequest?: ImportFinalizeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImportWorkspaceResponse> {
            return localVarFp.apiWorkspacesImportFinishPut(importFinalizeRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImportImageRequest} [importImageRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportImagePut(importImageRequest?: ImportImageRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImportWorkspaceResponse> {
            return localVarFp.apiWorkspacesImportImagePut(importImageRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImportRelationshipsRequest} [importRelationshipsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportRelationshipsPut(importRelationshipsRequest?: ImportRelationshipsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImportWorkspaceResponse> {
            return localVarFp.apiWorkspacesImportRelationshipsPut(importRelationshipsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImportWorkspaceStartRequest} [importWorkspaceStartRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportStartPut(importWorkspaceStartRequest?: ImportWorkspaceStartRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImportWorkspaceResponse> {
            return localVarFp.apiWorkspacesImportStartPut(importWorkspaceStartRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImportViewConfigurationRequest} [importViewConfigurationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportViewconfigurationPut(importViewConfigurationRequest?: ImportViewConfigurationRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImportWorkspaceResponse> {
            return localVarFp.apiWorkspacesImportViewconfigurationPut(importViewConfigurationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ImportViewsRequest} [importViewsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkspacesImportViewsPut(importViewsRequest?: ImportViewsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ImportWorkspaceResponse> {
            return localVarFp.apiWorkspacesImportViewsPut(importViewsRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WorkspacesImportApi - object-oriented interface
 */
export class WorkspacesImportApi extends BaseAPI {
    /**
     * 
     * @param {ImportClearDecisionsRequest} [importClearDecisionsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiWorkspacesImportCleardecisionsPut(importClearDecisionsRequest?: ImportClearDecisionsRequest, options?: RawAxiosRequestConfig) {
        return WorkspacesImportApiFp(this.configuration).apiWorkspacesImportCleardecisionsPut(importClearDecisionsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImportClearDocItemsRequest} [importClearDocItemsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiWorkspacesImportCleardocitemsPost(importClearDocItemsRequest?: ImportClearDocItemsRequest, options?: RawAxiosRequestConfig) {
        return WorkspacesImportApiFp(this.configuration).apiWorkspacesImportCleardocitemsPost(importClearDocItemsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImportDecisionRequest} [importDecisionRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiWorkspacesImportDecisionPut(importDecisionRequest?: ImportDecisionRequest, options?: RawAxiosRequestConfig) {
        return WorkspacesImportApiFp(this.configuration).apiWorkspacesImportDecisionPut(importDecisionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImportDecisionsLinksRequest} [importDecisionsLinksRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiWorkspacesImportDecisionlinksPut(importDecisionsLinksRequest?: ImportDecisionsLinksRequest, options?: RawAxiosRequestConfig) {
        return WorkspacesImportApiFp(this.configuration).apiWorkspacesImportDecisionlinksPut(importDecisionsLinksRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImportDocumentationRequest} [importDocumentationRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiWorkspacesImportDocumentationPut(importDocumentationRequest?: ImportDocumentationRequest, options?: RawAxiosRequestConfig) {
        return WorkspacesImportApiFp(this.configuration).apiWorkspacesImportDocumentationPut(importDocumentationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImportElementsRequest} [importElementsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiWorkspacesImportElementsPut(importElementsRequest?: ImportElementsRequest, options?: RawAxiosRequestConfig) {
        return WorkspacesImportApiFp(this.configuration).apiWorkspacesImportElementsPut(importElementsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImportFinalizeRequest} [importFinalizeRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiWorkspacesImportFinishPut(importFinalizeRequest?: ImportFinalizeRequest, options?: RawAxiosRequestConfig) {
        return WorkspacesImportApiFp(this.configuration).apiWorkspacesImportFinishPut(importFinalizeRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImportImageRequest} [importImageRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiWorkspacesImportImagePut(importImageRequest?: ImportImageRequest, options?: RawAxiosRequestConfig) {
        return WorkspacesImportApiFp(this.configuration).apiWorkspacesImportImagePut(importImageRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImportRelationshipsRequest} [importRelationshipsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiWorkspacesImportRelationshipsPut(importRelationshipsRequest?: ImportRelationshipsRequest, options?: RawAxiosRequestConfig) {
        return WorkspacesImportApiFp(this.configuration).apiWorkspacesImportRelationshipsPut(importRelationshipsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImportWorkspaceStartRequest} [importWorkspaceStartRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiWorkspacesImportStartPut(importWorkspaceStartRequest?: ImportWorkspaceStartRequest, options?: RawAxiosRequestConfig) {
        return WorkspacesImportApiFp(this.configuration).apiWorkspacesImportStartPut(importWorkspaceStartRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImportViewConfigurationRequest} [importViewConfigurationRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiWorkspacesImportViewconfigurationPut(importViewConfigurationRequest?: ImportViewConfigurationRequest, options?: RawAxiosRequestConfig) {
        return WorkspacesImportApiFp(this.configuration).apiWorkspacesImportViewconfigurationPut(importViewConfigurationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ImportViewsRequest} [importViewsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiWorkspacesImportViewsPut(importViewsRequest?: ImportViewsRequest, options?: RawAxiosRequestConfig) {
        return WorkspacesImportApiFp(this.configuration).apiWorkspacesImportViewsPut(importViewsRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

