/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AutomaticLayout
 */
export interface AutomaticLayout {
    /**
     * 
     * @type {string}
     * @memberof AutomaticLayout
     */
    'implementation'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AutomaticLayout
     */
    'rankDirection'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AutomaticLayout
     */
    'rankSeparation'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AutomaticLayout
     */
    'nodeSeparation'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AutomaticLayout
     */
    'edgeSeparation'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof AutomaticLayout
     */
    'vertices'?: boolean | null;
}

