/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DynamicRelationshipView
 */
export interface DynamicRelationshipView {
    /**
     * 
     * @type {string}
     * @memberof DynamicRelationshipView
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DynamicRelationshipView
     */
    'description'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DynamicRelationshipView
     */
    'response'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof DynamicRelationshipView
     */
    'order'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DynamicRelationshipView
     */
    'routing'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DynamicRelationshipView
     */
    'position'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DynamicRelationshipView
     */
    'sourceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DynamicRelationshipView
     */
    'destinationId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DynamicRelationshipView
     */
    'baseRelationshipId'?: string | null;
}

