/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ImageView
 */
export interface ImageView {
    /**
     * 
     * @type {string}
     * @memberof ImageView
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageView
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageView
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageView
     */
    'key'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageView
     */
    'workspaceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageView
     */
    'viewType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageView
     */
    'elementId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageView
     */
    'content'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageView
     */
    'contentType'?: string | null;
}

