/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { StructurizrWorkspace } from './structurizr-workspace';

/**
 * 
 * @export
 * @interface ImportWorkspaceRequest
 */
export interface ImportWorkspaceRequest {
    /**
     * 
     * @type {string}
     * @memberof ImportWorkspaceRequest
     */
    'workspaceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImportWorkspaceRequest
     */
    'importKey'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImportWorkspaceRequest
     */
    'sourceLink'?: string | null;
    /**
     * 
     * @type {StructurizrWorkspace}
     * @memberof ImportWorkspaceRequest
     */
    'workspaceData'?: StructurizrWorkspace;
}

