/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StructurizrRelationshipStyle
 */
export interface StructurizrRelationshipStyle {
    /**
     * 
     * @type {string}
     * @memberof StructurizrRelationshipStyle
     */
    'tag'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StructurizrRelationshipStyle
     */
    'thickness'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrRelationshipStyle
     */
    'color'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StructurizrRelationshipStyle
     */
    'fontSize'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StructurizrRelationshipStyle
     */
    'width'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof StructurizrRelationshipStyle
     */
    'dashed'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrRelationshipStyle
     */
    'routing'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StructurizrRelationshipStyle
     */
    'position'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StructurizrRelationshipStyle
     */
    'opacity'?: number | null;
}

