/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StructurizrElementStyle
 */
export interface StructurizrElementStyle {
    /**
     * 
     * @type {string}
     * @memberof StructurizrElementStyle
     */
    'tag'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StructurizrElementStyle
     */
    'width'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StructurizrElementStyle
     */
    'height'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrElementStyle
     */
    'background'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrElementStyle
     */
    'stroke'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrElementStyle
     */
    'strokeWidth'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrElementStyle
     */
    'color'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StructurizrElementStyle
     */
    'fontSize'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrElementStyle
     */
    'shape'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrElementStyle
     */
    'icon'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrElementStyle
     */
    'border'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StructurizrElementStyle
     */
    'opacity'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof StructurizrElementStyle
     */
    'metadata'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof StructurizrElementStyle
     */
    'description'?: boolean | null;
}

