/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkspaceCatalogElement
 */
export interface WorkspaceCatalogElement {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCatalogElement
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCatalogElement
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCatalogElement
     */
    'type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCatalogElement
     */
    'description'?: string | null;
}

