/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkspaceView
 */
export interface WorkspaceView {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceView
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceView
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceView
     */
    'viewType'?: string | null;
}

