/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { StructurizrAnimationStep } from './structurizr-animation-step';
// May contain unused imports in some cases
// @ts-ignore
import { StructurizrAutomaticLayout } from './structurizr-automatic-layout';
// May contain unused imports in some cases
// @ts-ignore
import { StructurizrDimensions } from './structurizr-dimensions';
// May contain unused imports in some cases
// @ts-ignore
import { StructurizrElementView } from './structurizr-element-view';
// May contain unused imports in some cases
// @ts-ignore
import { StructurizrRelationshipView } from './structurizr-relationship-view';

/**
 * 
 * @export
 * @interface StructurizrSystemLandscapeView
 */
export interface StructurizrSystemLandscapeView {
    /**
     * 
     * @type {string}
     * @memberof StructurizrSystemLandscapeView
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrSystemLandscapeView
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrSystemLandscapeView
     */
    'key'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrSystemLandscapeView
     */
    'paperSize'?: string | null;
    /**
     * 
     * @type {StructurizrDimensions}
     * @memberof StructurizrSystemLandscapeView
     */
    'dimensions'?: StructurizrDimensions;
    /**
     * 
     * @type {StructurizrAutomaticLayout}
     * @memberof StructurizrSystemLandscapeView
     */
    'automaticLayout'?: StructurizrAutomaticLayout;
    /**
     * 
     * @type {boolean}
     * @memberof StructurizrSystemLandscapeView
     */
    'enterpriseBoundaryVisible'?: boolean | null;
    /**
     * 
     * @type {Array<StructurizrElementView>}
     * @memberof StructurizrSystemLandscapeView
     */
    'elements'?: Array<StructurizrElementView> | null;
    /**
     * 
     * @type {Array<StructurizrRelationshipView>}
     * @memberof StructurizrSystemLandscapeView
     */
    'relationships'?: Array<StructurizrRelationshipView> | null;
    /**
     * 
     * @type {Array<StructurizrAnimationStep>}
     * @memberof StructurizrSystemLandscapeView
     */
    'animations'?: Array<StructurizrAnimationStep> | null;
}

