/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { StructurizrVertex } from './structurizr-vertex';

/**
 * 
 * @export
 * @interface StructurizrRelationshipView
 */
export interface StructurizrRelationshipView {
    /**
     * 
     * @type {string}
     * @memberof StructurizrRelationshipView
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrRelationshipView
     */
    'description'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof StructurizrRelationshipView
     */
    'response'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrRelationshipView
     */
    'order'?: string | null;
    /**
     * 
     * @type {StructurizrVertex}
     * @memberof StructurizrRelationshipView
     */
    'vertices'?: StructurizrVertex;
    /**
     * 
     * @type {string}
     * @memberof StructurizrRelationshipView
     */
    'routing'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StructurizrRelationshipView
     */
    'position'?: number | null;
}

