/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { StructurizrElementStyle } from './structurizr-element-style';
// May contain unused imports in some cases
// @ts-ignore
import { StructurizrRelationshipStyle } from './structurizr-relationship-style';

/**
 * 
 * @export
 * @interface StructurizrConfigurationStyles
 */
export interface StructurizrConfigurationStyles {
    /**
     * 
     * @type {Array<StructurizrElementStyle>}
     * @memberof StructurizrConfigurationStyles
     */
    'elements'?: Array<StructurizrElementStyle> | null;
    /**
     * 
     * @type {Array<StructurizrRelationshipStyle>}
     * @memberof StructurizrConfigurationStyles
     */
    'relationships'?: Array<StructurizrRelationshipStyle> | null;
}

