/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WorkspaceView } from './workspace-view';

/**
 * 
 * @export
 * @interface Workspace
 */
export interface Workspace {
    /**
     * 
     * @type {string}
     * @memberof Workspace
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Workspace
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Workspace
     */
    'description'?: string | null;
    /**
     * 
     * @type {Array<WorkspaceView>}
     * @memberof Workspace
     */
    'views'?: Array<WorkspaceView> | null;
}

