using CommandLine;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DocuEye.CLI
{
    public class CommandLineOptions
    {
        [Option("import", Required = true, HelpText = "Import mode. Currently only posible value is workspace")]
        public string Import { get; set; } = null!;
        [Option("docueyeAddress", Required = true, HelpText = "DocuEye address ex. http://localhost:8080.")]
        public string DocueyeAddress { get; set; } = null!;
        [Option("adminToken", Required = true, HelpText = "The Admin token from DocuEye configuration.")]
        public string AdminToken { get; set; } = null!;
        [Option("workspaceFile", Required = true, HelpText = "Path to workspace.json file, generated by structuriz cli.")]
        public string WorkspaceFile { get; set; } = null!;
        [Option("workspaceId", Required = false, HelpText = "The ID of the Workspace. If not provided the new workspace will be created. Also if workspace with given id does not exists new workspace will be created.")]
        public string? WorkspaceId { get; set; }
        [Option("importKey", Required = true, HelpText = "Unique import key. If not provided, one will be generated.")]
        public string ImportKey { get; set; } = null!;
        [Option("sourceLink", Required = false, HelpText = "Link to source version from whitch workspace is imported ex. link to PR or commit on github.")]
        public string? SourceLink { get; set; }

    }
}
