/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { type DeploymentNodeRelationshipItem } from './deployment-node-relationship-item';

/**
 * 
 * @export
 * @interface DeploymentNodeRelationship
 */
export interface DeploymentNodeRelationship {
    /**
     * 
     * @type {string}
     * @memberof DeploymentNodeRelationship
     */
    'sourceNodeId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeploymentNodeRelationship
     */
    'sourceNodeName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeploymentNodeRelationship
     */
    'sourceNodeTechnology'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeploymentNodeRelationship
     */
    'destinationNodeId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeploymentNodeRelationship
     */
    'destinationNodeName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeploymentNodeRelationship
     */
    'destinationTechnology'?: string | null;
    /**
     * 
     * @type {Array<DeploymentNodeRelationshipItem>}
     * @memberof DeploymentNodeRelationship
     */
    'items'?: Array<DeploymentNodeRelationshipItem> | null;
}

