/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export interface ElementToImport {
    'structurizrId'?: string | null;
    'structurizrParentId'?: string | null;
    'structurizrInstanceOfId'?: string | null;
    'dslId'?: string | null;
    'name'?: string | null;
    'url'?: string | null;
    'group'?: string | null;
    'tags'?: Array<string> | null;
    'type'?: string | null;
    'location'?: string | null;
    'technology'?: string | null;
    'description'?: string | null;
    'sourceCodeUrl'?: string | null;
    'ownerTeam'?: string | null;
    'properties'?: { [key: string]: string; } | null;
}

