/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { type ImageToImport } from './image-to-import';

/**
 * 
 * @export
 * @interface ImportImageRequest
 */
export interface ImportImageRequest {
    /**
     * 
     * @type {string}
     * @memberof ImportImageRequest
     */
    'workspaceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImportImageRequest
     */
    'importKey'?: string | null;
    /**
     * 
     * @type {ImageToImport}
     * @memberof ImportImageRequest
     */
    'image'?: ImageToImport;
}

