/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { type ElementToImport } from './element-to-import';

/**
 * 
 * @export
 * @interface ImportElementsRequest
 */
export interface ImportElementsRequest {
    /**
     * 
     * @type {Array<ElementToImport>}
     * @memberof ImportElementsRequest
     */
    'elements'?: Array<ElementToImport> | null;
    /**
     * 
     * @type {string}
     * @memberof ImportElementsRequest
     */
    'importKey'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImportElementsRequest
     */
    'workspaceId'?: string | null;
}

