/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { type DecisionLinkToImport } from './decision-link-to-import';

/**
 * 
 * @export
 * @interface ImportDecisionsLinksRequest
 */
export interface ImportDecisionsLinksRequest {
    /**
     * 
     * @type {string}
     * @memberof ImportDecisionsLinksRequest
     */
    'workspaceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImportDecisionsLinksRequest
     */
    'importKey'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImportDecisionsLinksRequest
     */
    'documentationId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImportDecisionsLinksRequest
     */
    'decisionDslId'?: string | null;
    /**
     * 
     * @type {Array<DecisionLinkToImport>}
     * @memberof ImportDecisionsLinksRequest
     */
    'decisionsLinks'?: Array<DecisionLinkToImport> | null;
}

