/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { type RelationshipToImport } from './relationship-to-import';

/**
 * 
 * @export
 * @interface ImportRelationshipsRequest
 */
export interface ImportRelationshipsRequest {
    /**
     * 
     * @type {Array<RelationshipToImport>}
     * @memberof ImportRelationshipsRequest
     */
    'relationships'?: Array<RelationshipToImport> | null;
    /**
     * 
     * @type {string}
     * @memberof ImportRelationshipsRequest
     */
    'importKey'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImportRelationshipsRequest
     */
    'workspaceId'?: string | null;
}

