/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export interface ModelChange {
    'id'?: string | null;
    'workspaceId'?: string | null;
    'elementId'?: string | null;
    'relationshipId'?: string | null;
    'importId'?: string | null;
    'importKey'?: string | null;
    'importLink'?: string | null;
    'eventTime'?: string;
    'type'?: string | null;
    'description'?: string | null;
}

