/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RelationshipInViewToImport
 */
export interface RelationshipInViewToImport {
    /**
     * 
     * @type {string}
     * @memberof RelationshipInViewToImport
     */
    'structurizrId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RelationshipInViewToImport
     */
    'description'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof RelationshipInViewToImport
     */
    'response'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof RelationshipInViewToImport
     */
    'order'?: string | null;
}

