/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StructurizrDecision } from './structurizr-decision';
// May contain unused imports in some cases
// @ts-ignore
import type { StructurizrDocumentationSection } from './structurizr-documentation-section';
// May contain unused imports in some cases
// @ts-ignore
import type { StructurizrImage } from './structurizr-image';

/**
 * 
 * @export
 * @interface StructurizrDocumentation
 */
export interface StructurizrDocumentation {
    /**
     * 
     * @type {Array<StructurizrDocumentationSection>}
     * @memberof StructurizrDocumentation
     */
    'sections'?: Array<StructurizrDocumentationSection> | null;
    /**
     * 
     * @type {Array<StructurizrDecision>}
     * @memberof StructurizrDocumentation
     */
    'decisions'?: Array<StructurizrDecision> | null;
    /**
     * 
     * @type {Array<StructurizrImage>}
     * @memberof StructurizrDocumentation
     */
    'images'?: Array<StructurizrImage> | null;
}

