/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StructurizrRelationship } from './structurizr-relationship';

/**
 * 
 * @export
 * @interface StructurizrContainerInstance
 */
export interface StructurizrContainerInstance {
    /**
     * 
     * @type {string}
     * @memberof StructurizrContainerInstance
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrContainerInstance
     */
    'containerId'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StructurizrContainerInstance
     */
    'instanceId'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrContainerInstance
     */
    'environment'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrContainerInstance
     */
    'tags'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrContainerInstance
     */
    'group'?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof StructurizrContainerInstance
     */
    'properties'?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<StructurizrRelationship>}
     * @memberof StructurizrContainerInstance
     */
    'relationships'?: Array<StructurizrRelationship> | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrContainerInstance
     */
    'dslId'?: string | null;
}

