/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StructurizrComponentView } from './structurizr-component-view';
// May contain unused imports in some cases
// @ts-ignore
import type { StructurizrConfiguration } from './structurizr-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { StructurizrContainerView } from './structurizr-container-view';
// May contain unused imports in some cases
// @ts-ignore
import type { StructurizrDeploymentView } from './structurizr-deployment-view';
// May contain unused imports in some cases
// @ts-ignore
import type { StructurizrDynamicView } from './structurizr-dynamic-view';
// May contain unused imports in some cases
// @ts-ignore
import type { StructurizrFilteredView } from './structurizr-filtered-view';
// May contain unused imports in some cases
// @ts-ignore
import type { StructurizrImageView } from './structurizr-image-view';
// May contain unused imports in some cases
// @ts-ignore
import type { StructurizrSystemContextView } from './structurizr-system-context-view';
// May contain unused imports in some cases
// @ts-ignore
import type { StructurizrSystemLandscapeView } from './structurizr-system-landscape-view';

/**
 * 
 * @export
 * @interface StructurizrViews
 */
export interface StructurizrViews {
    /**
     * 
     * @type {Array<StructurizrSystemLandscapeView>}
     * @memberof StructurizrViews
     */
    'systemLandscapeViews'?: Array<StructurizrSystemLandscapeView> | null;
    /**
     * 
     * @type {Array<StructurizrSystemContextView>}
     * @memberof StructurizrViews
     */
    'systemContextViews'?: Array<StructurizrSystemContextView> | null;
    /**
     * 
     * @type {Array<StructurizrContainerView>}
     * @memberof StructurizrViews
     */
    'containerViews'?: Array<StructurizrContainerView> | null;
    /**
     * 
     * @type {Array<StructurizrComponentView>}
     * @memberof StructurizrViews
     */
    'componentViews'?: Array<StructurizrComponentView> | null;
    /**
     * 
     * @type {Array<StructurizrDynamicView>}
     * @memberof StructurizrViews
     */
    'dynamicViews'?: Array<StructurizrDynamicView> | null;
    /**
     * 
     * @type {Array<StructurizrDeploymentView>}
     * @memberof StructurizrViews
     */
    'deploymentViews'?: Array<StructurizrDeploymentView> | null;
    /**
     * 
     * @type {Array<StructurizrFilteredView>}
     * @memberof StructurizrViews
     */
    'filteredViews'?: Array<StructurizrFilteredView> | null;
    /**
     * 
     * @type {Array<StructurizrImageView>}
     * @memberof StructurizrViews
     */
    'imageViews'?: Array<StructurizrImageView> | null;
    /**
     * 
     * @type {StructurizrConfiguration}
     * @memberof StructurizrViews
     */
    'configuration'?: StructurizrConfiguration;
}

