/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StructurizrDecisionLink } from './structurizr-decision-link';

/**
 * 
 * @export
 * @interface StructurizrDecision
 */
export interface StructurizrDecision {
    /**
     * 
     * @type {string}
     * @memberof StructurizrDecision
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrDecision
     */
    'date'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrDecision
     */
    'status'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrDecision
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrDecision
     */
    'content'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrDecision
     */
    'format'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StructurizrDecision
     */
    'elementId'?: string | null;
    /**
     * 
     * @type {Array<StructurizrDecisionLink>}
     * @memberof StructurizrDecision
     */
    'links'?: Array<StructurizrDecisionLink> | null;
}

