/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TerminologyToImport
 */
export interface TerminologyToImport {
    /**
     * 
     * @type {string}
     * @memberof TerminologyToImport
     */
    'enterprise'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TerminologyToImport
     */
    'person'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TerminologyToImport
     */
    'softwareSystem'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TerminologyToImport
     */
    'container'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TerminologyToImport
     */
    'component'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TerminologyToImport
     */
    'code'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TerminologyToImport
     */
    'deploymentNode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TerminologyToImport
     */
    'relationship'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TerminologyToImport
     */
    'infrastructureNode'?: string | null;
}

