/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



// May contain unused imports in some cases
// @ts-ignore
import type { ElementStyle } from './element-style';
// May contain unused imports in some cases
// @ts-ignore
import type { RelationshipStyle } from './relationship-style';
// May contain unused imports in some cases
// @ts-ignore
import type { Terminology } from './terminology';

export interface ViewConfiguration {
    'id'?: string | null;
    'elementStyles'?: Array<ElementStyle> | null;
    'relationshipStyles'?: Array<RelationshipStyle> | null;
    'themes'?: Array<string> | null;
    'terminology'?: Terminology;
    'groupSeparator'?: string | null;
}

