/* tslint:disable */
/* eslint-disable */
/**
 * DocuEye.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



// May contain unused imports in some cases
// @ts-ignore
import type { ElementInViewToImport } from './element-in-view-to-import';
// May contain unused imports in some cases
// @ts-ignore
import type { RelationshipInViewToImport } from './relationship-in-view-to-import';
// May contain unused imports in some cases
// @ts-ignore
import type { ViewAutomaticLayout } from './view-automatic-layout';

export interface ViewToImport {
    'viewType'?: string | null;
    'title'?: string | null;
    'description'?: string | null;
    'key'?: string | null;
    'paperSize'?: string | null;
    'elements'?: Array<ElementInViewToImport> | null;
    'relationships'?: Array<RelationshipInViewToImport> | null;
    'structurizrElementId'?: string | null;
    'externalBoundariesVisible'?: boolean | null;
    'automaticLayout'?: ViewAutomaticLayout;
    'content'?: string | null;
    'contentType'?: string | null;
    'baseViewKey'?: string | null;
    'mode'?: string | null;
    'tags'?: Array<string> | null;
}

