name: Deploy docueye cli image
run-name: 'Deploy docueye cli image ${{ github.event.inputs.docueye_cli_version }}' 
on: 
  workflow_dispatch:
    inputs:
      docueye_cli_version:
        description: 'DocuEye cli version'
        required: true
jobs:
  deploy_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build docueye cli image
      run: docker build -t jacekzwpl/docueye-cli:${{ github.event.inputs.docueye_cli_version }} -f ./Source/DocuEye.CLI/Dockerfile .
    - name: Tag with latest
      run: docker tag jacekzwpl/docueye-cli:${{ github.event.inputs.docueye_cli_version }} jacekzwpl/docueye:latest
    - name: Push Docker image ${{ github.event.inputs.docueye_cli_version }}
      run: docker push jacekzwpl/docueye-cli:${{ github.event.inputs.docueye_cli_version }}
    - name: Push Docker image latest
      run: docker push jacekzwpl/docueye-cli:latest
    