name: PR Check
run-name: PR Check
on: 
  push: 
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore DocuEye.sln
    - name: Build .net
      run: dotnet build DocuEye.sln --no-restore
    - name: Test
      run: dotnet test DocuEye.sln --no-restore