name: PR Check
run-name: PR Check
on: 
  push: 
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Test
      run: dotnet test DocuEye.sln
    - name: Build docueye
      run: docker build -t jacekzwpl/docueye:test-build -f ./Source/DocuEye.Web/Dockerfile .
    - name: Build docueye-cli
      run: docker build -t jacekzwpl/docueye-cli:test-build -f ./Source/DocuEye.Cli/Dockerfile .